"""Generated promoted VocabQuest reading passages."""

from __future__ import annotations


VOCABQUEST_PROMOTED_PASSAGES = [{'id': 'rp_vq_792afa73f104',
  'passage_code': 'VQ_792AFA73F104',
  'title': 'Reading Quest [Literature]: PET全_Page_61_03261514',
  'body_text': 'Sarah arrived at the old farm, her room still looking quite untidy after the long journey. She had '
               'previously visited this place with her history teacher to study local custom. Despite the cool breeze, '
               'she felt a strong urge to hike up the hill. She needed to practise her violin, but her arm felt sore. '
               'In the kitchen, there was nothing but a bowl of fruit and some sauce. She grabbed an eraser and a '
               'notebook, intending to write a play. Suddenly, she heard a frightening noise—a band of horses had '
               'escaped their enclosure! It was necessary to call the owner. With great effort, she managed to secure '
               'the gate, feeling a sense of success. She was disappointed by the damage done to the fence, but she '
               'knew the rider was safe. Later, she enjoyed some dessert with extra sugar while listening to '
               'electrical music on her portable DVD player. She felt that life here did not depend on expensive '
               'software; it was a simple, quiet life, far from the busy airport where she had started her day.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'literature',
  'word_count': 178,
  'topic': 'PET_part_3',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_792afa73f104',
               'source_session_id': '792afa73-f104-474b-a2df-9aa6aff77563',
               'generated_missing_skill': 'structure_author_purpose'},
  'items': [{'id': 'ri_vq_792afa73f104_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What does the author suggest about Sarah's life at the farm?",
             'choices': {'A': 'It relies on modern software',
                         'B': 'It is complex and stressful',
                         'C': 'It does not depend on technology',
                         'D': 'It is similar to living near an airport'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': 'The text says life there did not depend on expensive software, reinforcing the word '
                                 "'depend'.",
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_792afa73f104_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'How did Sarah feel about the state of her room when she arrived?',
             'choices': {'A': 'It was very clean',
                         'B': 'It was untidy',
                         'C': 'It was full of litter',
                         'D': 'It was already organized'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The text explicitly states her room was looking quite untidy. 'Untidy' is the "
                                 'targeted vocabulary.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_792afa73f104_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why was Sarah disappointed?',
             'choices': {'A': 'Because she could not play her violin',
                         'B': 'Because the weather was bad',
                         'C': 'Because the fence was damaged',
                         'D': 'Because she had nothing to eat'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': 'Sarah felt disappointed by the damage done to the fence caused by the horses.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_792afa73f104_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Which word best describes the action Sarah took to fix the gate?',
             'choices': {'A': 'Lazy', 'B': 'Effort', 'C': 'Necessary', 'D': 'Frightening'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "Sarah used great effort to secure the gate, showcasing the word 'effort'.",
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_792afa73f104_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why does the writer include several specific details in the passage?',
             'choices': {'A': 'To show how the main idea develops through events or examples',
                         'B': 'To list unrelated facts without a purpose',
                         'C': 'To explain a grammar rule',
                         'D': 'To introduce a different passage'},
             'correct_choice': 'A',
             'rationales': {'A': 'The details help connect the passage events and ideas.',
                            'B': 'The details support the passage rather than being unrelated.',
                            'C': 'The passage does not focus on a grammar rule.',
                            'D': 'The details belong to this passage.'}}]},
 {'id': 'rp_vq_5f20d02399b3',
  'passage_code': 'VQ_5F20D02399B3',
  'title': 'Reading Quest [Vocabulary]: PET全_Page_43_03261514',
  'body_text': 'Last century, our town began a curriculum project to improve the local park. Recently, I joined an '
               'expedition across the old street to see the new garden. My favourite part is the pool where water '
               'lilies grow. I sat on a wooden seat to watch the sunset, feeling responsible for keeping the area '
               'clean. I had brought some refreshments, including fresh cabbage, butter, flour, and a lemon, intending '
               'to grill something light. Suddenly, a boy started to cry because his bicycle tyre had a puncture. I '
               'wanted to save the day, so I offered to help him. I reminded him that a doctor lives nearby if he felt '
               'unfit. We chatted while he played a game on his screen to stay calm. He told me he was a fan of music '
               'and practiced the trumpet daily. Being there reminded me that small acts affect our community. Even '
               'though the day was off to a slow start, I enjoyed the peace of the universe away from the noise of '
               'parking cars. It was a lovely day, and I suppose I will return again soon.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'vocabulary',
  'word_count': 183,
  'topic': 'PET_part_4',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_5f20d02399b3',
               'source_session_id': '5f20d023-99b3-45d7-8553-246db3cea00c',
               'generated_missing_skill': ''},
  'items': [{'id': 'ri_vq_5f20d02399b3_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What is the narrator's main purpose in visiting the garden?",
             'choices': {'A': 'To conduct a scientific expedition',
                         'B': "To enjoy the sunset and the garden's environment",
                         'C': 'To look for a doctor',
                         'D': 'To participate in the town curriculum'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'The narrator mentions visiting to see the garden and sitting on a seat to watch the '
                                 'sunset, which shows they enjoyed the space. (Vocab: garden, sunset, enjoy)',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_5f20d02399b3_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why did the narrator feel responsible while in the park?',
             'choices': {'A': "They were in charge of the park's parking",
                         'B': 'They wanted to keep the area clean',
                         'C': 'They were fixing a tyre',
                         'D': 'They were a doctor'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'The passage says the narrator felt responsible for keeping the area clean.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_5f20d02399b3_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'How did the boy feel when his tyre broke?',
             'choices': {'A': 'He was angry at the narrator',
                         'B': 'He was playing a game on the screen',
                         'C': 'He was unhappy and started to cry',
                         'D': 'He was fit and healthy'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "The passage says the boy 'started to cry' because his tyre had a puncture. (Vocab: "
                                 'cry, tyre)',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_5f20d02399b3_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What does the word 'suppose' suggest about the narrator's plans?",
             'choices': {'A': 'They are forced to go back',
                         'B': 'They are certain they will return',
                         'C': 'They think they will return, but it is not 100% sure',
                         'D': 'They are forbidden from returning'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "'Suppose' indicates a belief or assumption rather than a definite scheduled event. "
                                 '(Vocab: suppose)',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_5f20d02399b3_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why does the narrator include the boy with the punctured tyre?',
             'choices': {'A': 'To show how a small act of help can affect the community',
                         'B': 'To explain why the town curriculum project failed',
                         'C': 'To introduce the doctor as the main character',
                         'D': 'To describe the rules of a screen game'},
             'correct_choice': 'A',
             'rationales': {'A': 'The incident shows the narrator offering help, which supports the later idea that '
                                 'small acts affect the community.',
                            'B': 'The passage does not say the project failed.',
                            'C': 'The doctor is only mentioned as someone nearby, not as the main character.',
                            'D': 'The screen game helps the boy stay calm, but it is not the purpose of the '
                                 'incident.'}}]},
 {'id': 'rp_vq_89dda07ee4d1',
  'passage_code': 'VQ_89DDA07EE4D1',
  'title': 'Reading Quest [Vocabulary]: PET全_Page_15_03261327',
  'body_text': 'As a journalist, I often travel to unique areas. Last week, I visited a beautiful green town in '
               'Ireland. I decided to write a blog about the local market. I stood in a long row of stalls, watching '
               'the busy atmosphere. Near a stall selling fresh tuna, a shy employee was putting items on a shelf. He '
               'carefully picked a packet of spices from a drawer beneath the counter. I asked him about the local '
               "menu, and he suggested the grilled fish. When I offered to pay, he said, 'No, you owe me nothing; it's "
               "on the house!' I couldn't help but laugh at his kindness. Later, I sat in a comfortable armchair in my "
               'hotel room. The room was dark, but a warm lamp provided light. I thought about the human connection I '
               'felt today, far away from the stress of the city. I tried to understand the meaning of travel, '
               'realizing it is not just about visiting places, but about the people you meet. There was no need to '
               'worry about my former life or the language barrier. Here, everything felt mild and peaceful, a sharp '
               'contrast to the news of war often seen on television.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'vocabulary',
  'word_count': 198,
  'topic': 'PET_part_3',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_89dda07ee4d1',
               'source_session_id': '89dda07e-e4d1-4902-be0c-13fdc4d3ad07',
               'generated_missing_skill': 'structure_author_purpose'},
  'items': [{'id': 'ri_vq_89dda07ee4d1_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What is the narrator's main purpose for this trip?",
             'choices': {'A': 'To report on a war',
                         'B': 'To find a job as an employee',
                         'C': 'To write a blog post about the location',
                         'D': 'To buy equipment for his office'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "The narrator states, 'I decided to write a blog about the local market'.",
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_89dda07ee4d1_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Where does the narrator find themselves at the beginning of the story?',
             'choices': {'A': 'In a dark office in the city',
                         'B': 'In a green area of Ireland',
                         'C': 'At a basketball court',
                         'D': 'Inside a supermarket warehouse'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The passage explicitly mentions 'I visited a beautiful green town in Ireland'.",
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_89dda07ee4d1_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'How does the narrator describe their experience in the hotel room?',
             'choices': {'A': 'They felt a lot of stress',
                         'B': 'They were worried about their former job',
                         'C': 'They felt peaceful and reflective',
                         'D': 'They were unable to understand the local language'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': 'The author contrasts the experience with city stress, describing the atmosphere as '
                                 "'mild and peaceful'.",
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_89dda07ee4d1_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What does the narrator mean when they say, 'You owe me nothing'?",
             'choices': {'A': 'The food was expensive',
                         'B': 'The narrator had already paid',
                         'C': 'The food was free of charge',
                         'D': 'The employee did not understand the bill'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "The phrase 'on the house' implies the meal was complimentary and no payment was "
                                 'required.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_89dda07ee4d1_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why does the writer include several specific details in the passage?',
             'choices': {'A': 'To show how the main idea develops through events or examples',
                         'B': 'To list unrelated facts without a purpose',
                         'C': 'To explain a grammar rule',
                         'D': 'To introduce a different passage'},
             'correct_choice': 'A',
             'rationales': {'A': 'The details help connect the passage events and ideas.',
                            'B': 'The details support the passage rather than being unrelated.',
                            'C': 'The passage does not focus on a grammar rule.',
                            'D': 'The details belong to this passage.'}}]},
 {'id': 'rp_vq_6c9459a3d134',
  'passage_code': 'VQ_6C9459A3D134',
  'title': 'Reading Quest [Vocabulary]: PET全_Page_4_03261327',
  'body_text': 'Living in the city is often stressful, so I decided to depart for the quiet countryside. I made a '
               'reservation at a cosy cabin near a beautiful lake. Before I left, I checked the refrigerator for a '
               'quick snack, grabbing some beans and an apple. The journey by aeroplane and then bus was long, but it '
               'was a great achievement to reach the cabin after careful preparation. It was quiet, but I could hear a '
               'distant drum sound and the curious croaking of a frog near the water. My friend, a very sociable '
               'person who loves to chat, sent me a video update of the city. I laughed, wearing my favourite gray '
               'sweatshirt. I did not want to waste time, so I walked in the direction of the woods. I felt a sense of '
               'peace, far from the busy streets. I met a local leader who told me about the area’s engineering '
               'history. We had a delicious lunch while we talk about life. It was a perfect escape; I did not feel '
               'the need to invite anyone else. Being still in nature provides more comfort than anything else.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'vocabulary',
  'word_count': 188,
  'topic': 'PET_part_3',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_6c9459a3d134',
               'source_session_id': '6c9459a3-d134-4513-bb2e-b95f2721d8fa',
               'generated_missing_skill': 'structure_author_purpose'},
  'items': [{'id': 'ri_vq_6c9459a3d134_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why did the author choose to go to the countryside?',
             'choices': {'A': 'To start a career in engineering',
                         'B': 'To escape a stressful city life',
                         'C': 'To meet the local leader',
                         'D': 'To attend a live concert'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The passage states that living in the city is 'stressful', prompting the author to "
                                 'leave for the countryside.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_6c9459a3d134_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'What did the author do before leaving for the trip?',
             'choices': {'A': 'He bought a new gray sweatshirt.',
                         'B': 'He prepared food from the refrigerator.',
                         'C': 'He invited his friend to join him.',
                         'D': 'He practiced playing the drum.'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The text mentions checking the 'refrigerator' for a 'quick snack' before departing.",
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_6c9459a3d134_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'How did the author feel about the quiet surroundings?',
             'choices': {'A': 'Lonely and bored',
                         'B': 'Comforted and peaceful',
                         'C': 'Curious but worried',
                         'D': 'Confused by the sounds'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The author mentions that being still in nature provides a 'sense' of peace and "
                                 "'comfort'.",
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_6c9459a3d134_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What does the word 'depart' mean in this context?",
             'choices': {'A': 'To arrive at a place',
                         'B': 'To stay in one spot',
                         'C': 'To leave a place',
                         'D': 'To change direction'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "The author decided to 'depart' for the countryside, which means leaving their "
                                 'current location to travel elsewhere.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_6c9459a3d134_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why does the writer include several specific details in the passage?',
             'choices': {'A': 'To show how the main idea develops through events or examples',
                         'B': 'To list unrelated facts without a purpose',
                         'C': 'To explain a grammar rule',
                         'D': 'To introduce a different passage'},
             'correct_choice': 'A',
             'rationales': {'A': 'The details help connect the passage events and ideas.',
                            'B': 'The details support the passage rather than being unrelated.',
                            'C': 'The passage does not focus on a grammar rule.',
                            'D': 'The details belong to this passage.'}}]},
 {'id': 'rp_vq_f7dd8057bc29',
  'passage_code': 'VQ_F7DD8057BC29',
  'title': 'Reading Quest [Vocabulary]: PET全_Page_10_03261327',
  'body_text': 'On a sunny September morning, my wife and I decided to visit the local mall located on a nearby island '
               'in the southeast. I felt quite stressed lately due to political news, so I wanted an outdoor change. I '
               'wore my favorite blue T-shirt and grabbed my pen to write a list. Actually, the mall was gorgeous, but '
               'my luck turned bad when I felt sick after eating a spicy burger with a local chilli. I started to '
               'cough, and my wife asked me to quickly wrap my head in a scarf. We had to demand a refund for the '
               'meal, which was not satisfactory. Despite this, I was intelligent enough to carry my own medicine. We '
               'left the mall to watch a kite flying in the wind. We might return, but I need to apologise to my wife '
               'for ruining our time. Carrying knowledge about my health is important, even if the experience was '
               'terrible. I feel much better now that I have had time to wake up properly from that burning stomach '
               'pain.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'vocabulary',
  'word_count': 175,
  'topic': 'PET_part_4',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_f7dd8057bc29',
               'source_session_id': 'f7dd8057-bc29-40f7-a224-a8e656cbf0be',
               'generated_missing_skill': 'structure_author_purpose'},
  'items': [{'id': 'ri_vq_f7dd8057bc29_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What is the author's overall attitude towards the trip?",
             'choices': {'A': 'He thought it was a perfect day',
                         'B': 'He thought it was a terrible experience',
                         'C': 'He was indifferent',
                         'D': 'He was happy he met his wife there'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The narrator describes the experience as 'terrible' due to the sickness and the "
                                 'ruined time. (词汇: terrible)',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_f7dd8057bc29_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why did the narrator go to the mall?',
             'choices': {'A': 'To buy a new T-shirt',
                         'B': 'To escape political stress',
                         'C': 'To meet his wife',
                         'D': 'To eat a spicy burger'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'The passage explicitly states he felt stressed due to political news and wanted an '
                                 'outdoor change. (词汇: stressed/political)',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_f7dd8057bc29_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What was the narrator's reaction to the bad meal?",
             'choices': {'A': 'He laughed at the situation',
                         'B': 'He asked for his money back',
                         'C': 'He stayed to eat another',
                         'D': 'He apologized to the waiter'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The text says they had to 'demand a refund', which means asking for money back. (词汇: "
                                 'demand)',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_f7dd8057bc29_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What does the word 'satisfactory' mean in this context?",
             'choices': {'A': 'Good enough', 'B': 'Very expensive', 'C': 'Extremely bad', 'D': 'Quickly prepared'},
             'correct_choice': 'A',
             'rationales': {'A': "The narrator demanded a refund because the meal was not 'satisfactory', meaning it "
                                 'failed to meet expectations. (词汇: satisfactory)',
                            'B': 'This choice is not the reviewed answer.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_f7dd8057bc29_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why does the writer include several specific details in the passage?',
             'choices': {'A': 'To show how the main idea develops through events or examples',
                         'B': 'To list unrelated facts without a purpose',
                         'C': 'To explain a grammar rule',
                         'D': 'To introduce a different passage'},
             'correct_choice': 'A',
             'rationales': {'A': 'The details help connect the passage events and ideas.',
                            'B': 'The details support the passage rather than being unrelated.',
                            'C': 'The passage does not focus on a grammar rule.',
                            'D': 'The details belong to this passage.'}}]},
 {'id': 'rp_vq_f649b491b3dd',
  'passage_code': 'VQ_F649B491B3DD',
  'title': 'Reading Quest [Informational]: PET全_Page_46_03261514',
  'body_text': 'In our modern world, the way we handle our resources is likely to have a major impact on the future. '
               'Many experts in economics suggest that our current method of consumption is not sustainable. We '
               'frequently see negative news about the environment, and it is a common prayer of many scientists that '
               'we change our habits before we pay a high price. Whether you are a professional athlete or a student, '
               'every action counts. For example, check the size of the heater you use and mend old clothes instead of '
               'buying new ones made of cheap material. Some people travel everywhere by car, but choosing to share a '
               'lift or walk toward your destination reduces your footprint. Even small changes, like eating more '
               'local vegetable pasta and avoiding coconut products that travel long distances, help. We should warn '
               'others about the waste we generate. It is also golden advice to treat the earth with respect, as if '
               'protecting a deep friendship. If we follow these steps, we might avoid the criminal waste of resources '
               'that current generations face. It is not just a dream; it is an essential deal for our survival.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'informational',
  'word_count': 192,
  'topic': 'informational',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_f649b491b3dd',
               'source_session_id': 'f649b491-b3dd-44c3-9b4e-ec32849bcfb3',
               'generated_missing_skill': 'main_idea'},
  'items': [{'id': 'ri_vq_f649b491b3dd_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'What is the passage mainly about?',
             'choices': {'A': 'The central situation in Reading Quest [Informational]: PET全_Page_46_03261514',
                         'B': 'A list of unrelated facts',
                         'C': 'A grammar lesson about one word',
                         'D': 'A completely different event'},
             'correct_choice': 'A',
             'rationales': {'A': 'This choice best summarizes the whole passage.',
                            'B': 'The details in the passage are connected, not unrelated.',
                            'C': 'The passage is a reading text, not a grammar lesson.',
                            'D': 'This choice does not match the passage.'}},
            {'id': 'ri_vq_f649b491b3dd_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'What is recommended regarding the clothes we own?',
             'choices': {'A': 'Buy new clothes every season.',
                         'B': 'Only wear expensive material.',
                         'C': 'Mend old items instead of replacing them.',
                         'D': 'Give them to a criminal.'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "The text explicitly suggests that we should 'mend' old clothes instead of buying new "
                                 "ones made of new 'material'.",
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_f649b491b3dd_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'What does the author suggest about our current way of living?',
             'choices': {'A': 'It is very effective and sustainable.',
                         'B': 'It is likely to cause future problems.',
                         'C': 'It is perfect and needs no changes.',
                         'D': 'It is only a problem for professional athletes.'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The passage states that the way we handle resources is 'likely' to have an impact, "
                                 "and experts suggest our current 'method' is not sustainable.",
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_f649b491b3dd_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'How does the author feel about the current news regarding the environment?',
             'choices': {'A': 'Positive and hopeful.',
                         'B': 'Angry and aggressive.',
                         'C': 'Negative and worrying.',
                         'D': 'Surprised and confused.'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "The author mentions that we 'frequently' see 'negative' news, suggesting a tone of "
                                 'concern.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_f649b491b3dd_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'What is the main purpose of this article?',
             'choices': {'A': 'To warn people about the danger of heaters.',
                         'B': 'To teach people how to cook vegetable pasta.',
                         'C': 'To encourage readers to follow sustainable habits.',
                         'D': 'To discuss the friendship between athletes.'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "The passage aims to 'warn' readers and suggests they 'follow' better habits to "
                                 'protect the future, making the main purpose educational.',
                            'D': 'This choice is not the reviewed answer.'}}]},
 {'id': 'rp_vq_ba84f6e272be',
  'passage_code': 'VQ_BA84F6E272BE',
  'title': 'Reading Quest [Literature]: PET全_Page_10_03261327',
  'body_text': 'In September, Arthur traveled to a remote island in the southeast for his vacation. Being an '
               'intelligent traveler, he knew the weather might change quickly. One afternoon, while enjoying a burger '
               'at a nearby mall, he started to cough. He felt sick, perhaps because the chilli in his food was too '
               'hot. He went outside to get some air, but a burning wind began to blow. He had to wrap himself in his '
               'thin T-shirt, which was a terrible mistake. Suddenly, he saw a boy struggling with a kite near the '
               'door of a shop. The wind was so strong that it could carry the boy away! Arthur quickly ran over to '
               "help. 'These toys are dangerous in this weather!' Arthur shouted. The boy apologized, saying he was "
               'stressed because it was his ninth attempt to fly it today. Arthur laughed and told him to go home. It '
               'was a different kind of experience, not exactly the gorgeous trip he expected, but it was a '
               'satisfactory memory nonetheless. Actually, he found that despite the bad weather, helping someone made '
               'the trip worthwhile. He sat on a bench, took out his pen, and wrote about his day, feeling happy that '
               'he had gained some local knowledge.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'literature',
  'word_count': 205,
  'topic': 'PET_part_3',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_ba84f6e272be',
               'source_session_id': 'ba84f6e2-72be-4c5f-aaba-6de3666d3154',
               'generated_missing_skill': 'structure_author_purpose'},
  'items': [{'id': 'ri_vq_ba84f6e272be_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What is the author's opinion about the trip at the end?",
             'choices': {'A': 'It was a terrible experience.',
                         'B': 'It was better than he expected.',
                         'C': 'He was dissatisfied with the island.',
                         'D': 'He felt the trip was satisfactory.'},
             'correct_choice': 'D',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'Arthur describes the day as a satisfactory memory because he enjoyed helping the '
                                 'boy. Word: satisfactory'}},
            {'id': 'ri_vq_ba84f6e272be_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why did Arthur feel sick in the mall?',
             'choices': {'A': 'He had a bad cold.',
                         'B': 'The food he ate was too spicy.',
                         'C': 'He was stressed about his flight.',
                         'D': 'He was allergic to the burger.'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'The passage mentions he started to cough after eating a burger with chilli, leading '
                                 'to him feeling sick. Word: chilli',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_ba84f6e272be_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What does the author mean by 'intelligent traveler'?",
             'choices': {'A': 'Someone who is wealthy.',
                         'B': 'Someone who prepares for changes.',
                         'C': 'Someone who loves flying.',
                         'D': 'Someone who speaks many languages.'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'Arthur is described as intelligent because he knew the weather might change, showing '
                                 'he is prepared. Word: intelligent',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_ba84f6e272be_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What does 'actually' imply in the final paragraph?",
             'choices': {'A': 'That the trip was easy.',
                         'B': 'That the reality was different from the bad weather conditions.',
                         'C': 'That Arthur is a professional writer.',
                         'D': "That he didn't like the island."},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The word 'actually' introduces the fact that despite the bad weather, he found the "
                                 'trip worthwhile. Word: actually',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_ba84f6e272be_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why does the writer include several specific details in the passage?',
             'choices': {'A': 'To show how the main idea develops through events or examples',
                         'B': 'To list unrelated facts without a purpose',
                         'C': 'To explain a grammar rule',
                         'D': 'To introduce a different passage'},
             'correct_choice': 'A',
             'rationales': {'A': 'The details help connect the passage events and ideas.',
                            'B': 'The details support the passage rather than being unrelated.',
                            'C': 'The passage does not focus on a grammar rule.',
                            'D': 'The details belong to this passage.'}}]},
 {'id': 'rp_vq_52b839573d65',
  'passage_code': 'VQ_52B839573D65',
  'title': 'Reading Quest [Literature]: PET全_Page_35_03261514',
  'body_text': 'In late November, during the heart of autumn, Clara went to visit her grandmother in a small house '
               'near the forest. Clara, a young engineer, had one clear object: to design a relaxation machine for her '
               'cousin. It was her first attempt at such a complex task, and she worked alone in the attic, hoping to '
               "pull together a quality prototype. She did not want to cheat by using someone else's blueprints; she "
               'believed she deserved to learn through her own effort. The worst part was the limit on her time, as '
               'she had an important appointment tomorrow. Outside, the scenery was historic and scary in its silence, '
               'but the mountains felt like a channel for her focus. She decided to dial back her stress, even though '
               'she felt badly about missing the local firework show. Her brain was tired, and she even dropped a pin '
               'on her toe, but she refused to quit. She remembered her grandmother saying that even if something is '
               'incorrect, the attempt is what matters most. By the time the moon rose, she had managed to attach the '
               'final piece, feeling she had achieved the furthest point of her creativity.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'literature',
  'word_count': 195,
  'topic': 'literature',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_52b839573d65',
               'source_session_id': '52b83957-3d65-47fc-8983-a2c99de252cf',
               'generated_missing_skill': 'structure_author_purpose'},
  'items': [{'id': 'ri_vq_52b839573d65_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What was Clara's primary goal at her grandmother's house?",
             'choices': {'A': 'To watch fireworks',
                         'B': 'To design a machine',
                         'C': 'To study history',
                         'D': 'To go for a ride'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'The passage states Clara had a clear object to design a relaxation machine.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_52b839573d65_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why did Clara work alone?',
             'choices': {'A': 'Because she had no friends',
                         'B': 'To ensure the quality of her own effort',
                         'C': 'Because her cousin was busy',
                         'D': 'Because she was lost in the forest'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'She did not want to cheat because she felt she deserved to learn through her own '
                                 'effort.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_52b839573d65_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'How did Clara feel about her work progress?',
             'choices': {'A': 'She felt very confident',
                         'B': 'She felt bad about missing the fireworks',
                         'C': 'She was happy to cheat',
                         'D': 'She hated the forest'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'Clara felt badly about missing the local firework show while working.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_52b839573d65_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What is the meaning of 'furthest' in the context of the story?",
             'choices': {'A': 'The shortest distance',
                         'B': 'The maximum limit of her creativity',
                         'C': 'A long way from the forest',
                         'D': 'The incorrect side of the room'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'It refers to reaching the furthest point of her creative capacity.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_52b839573d65_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'Why does the writer include several specific details in the passage?',
             'choices': {'A': 'To show how the main idea develops through events or examples',
                         'B': 'To list unrelated facts without a purpose',
                         'C': 'To explain a grammar rule',
                         'D': 'To introduce a different passage'},
             'correct_choice': 'A',
             'rationales': {'A': 'The details help connect the passage events and ideas.',
                            'B': 'The details support the passage rather than being unrelated.',
                            'C': 'The passage does not focus on a grammar rule.',
                            'D': 'The details belong to this passage.'}}]},
 {'id': 'rp_vq_253ea7923758',
  'passage_code': 'VQ_253EA7923758',
  'title': 'Reading Quest [Literature]: PET全_Page_57_03261514',
  'body_text': 'Arthur, an adult actor, sat at the crossroads of his career. He had just signed a contract to play a '
               'superhero, but he felt a strange disappointment. It was a usual winter, yet the weather was harsh. He '
               'pulled his handkerchief from his pocket, touched his chin, and wiped his throat as the heating in his '
               'dressing room failed. He looked at the newspaper, which mentioned the local government had failed to '
               "build a new ski slope. 'Anyway,' he whispered, 'I should be excited.' He checked his smartphone to see "
               'a dozen messages. His agent had also booked a charter flight to a snowy resort. He looked out the '
               'window at the white liquid falling from the sky. It reminded him of his education in the mountains '
               'during his early years. He was frightened of failing this role, but he knew being wise was essential. '
               'A second later, he realized the script was for a sequel to his previous film. He stood up, ready to '
               'start the third act. He had to be satisfied with the length of his journey, even if the road felt '
               'long.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'literature',
  'word_count': 186,
  'topic': 'PET_part_4',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_253ea7923758',
               'source_session_id': '253ea792-3758-4b20-8aff-2abee3d25213',
               'generated_missing_skill': ''},
  'items': [{'id': 'ri_vq_253ea7923758_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'What is the main idea of the passage?',
             'choices': {'A': 'Arthur is struggling with his job and personal life.',
                         'B': 'Arthur is preparing for a new superhero movie role.',
                         'C': 'Arthur is disappointed about a canceled ski trip.',
                         'D': "Arthur is worried about the government's education policy."},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'The passage primarily focuses on Arthur, an actor, reflecting on his career and his '
                                 'upcoming role as a superhero despite his personal anxieties.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_253ea7923758_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'What does Arthur do while waiting in his dressing room?',
             'choices': {'A': 'He writes a contract for his agent.',
                         'B': 'He reads news about a ski project.',
                         'C': 'He calls the government about the heating.',
                         'D': 'He practices his lines for the third time.'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'The text states he looked at the newspaper, which mentioned the local government '
                                 'failing to build a new ski slope.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_253ea7923758_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What can be inferred about Arthur's feelings toward his new role?",
             'choices': {'A': 'He is completely confident and happy.',
                         'B': 'He thinks it is a waste of his education.',
                         'C': 'He has mixed emotions and feels some pressure.',
                         'D': 'He wants to quit acting to go on a picnic.'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "Arthur says he 'should' be excited and feels frightened, suggesting he is nervous "
                                 'despite his success.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_253ea7923758_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "In the text, what does the word 'satisfied' mean?",
             'choices': {'A': 'Content or pleased with something.',
                         'B': "Annoyed by someone's behavior.",
                         'C': 'Confused about a difficult task.',
                         'D': 'Excited to start a new adventure.'},
             'correct_choice': 'A',
             'rationales': {'A': "In context, 'satisfied' describes Arthur wanting to feel content with the 'length of "
                                 "his journey' in his acting career.",
                            'B': 'This choice is not the reviewed answer.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_253ea7923758_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "Why does the author mention the 'heating' in the dressing room?",
             'choices': {'A': 'To describe the luxury of being an actor.',
                         'B': 'To explain why Arthur is feeling cold and unwell.',
                         'C': 'To show that the building is very old.',
                         'D': 'To illustrate the poor conditions of his current workplace.'},
             'correct_choice': 'D',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': "The author uses the broken heating to add to Arthur's sense of discomfort and "
                                 'dissatisfaction, highlighting his challenging environment.'}}]},
 {'id': 'rp_vq_3fcd767f3e99',
  'passage_code': 'VQ_3FCD767F3E99',
  'title': 'Reading Quest [Literature]: PET全_Page_59_03261514',
  'body_text': 'Arthur felt low as he drove his old car toward the southern region, hoping to reach the western coast '
               'before sunset. Unfortunately, his tank was running out of gas. He decided to stop at a small, purple '
               'hostel near the mountains. As he entered the kitchen, a young man, who seemed to be the keeper, was '
               'busy preparing a roast meal. The man held a metal bell and rang it, signaling it was time for the '
               'fifteenth guest to arrive. Arthur looked in the mirror above the sink, adjusting his coat. He felt '
               'crazy for taking this trip without a proper licence. He grabbed a glass of lemonade, feeling grateful '
               'for the simple comfort. A serious woman, clearly the headteacher of a local school, sat in the corner '
               'writing a composition about trade. She looked at Arthur and sighed, wishing he would not disappoint '
               "the locals with his loud music. 'Is this room permitted for me?' Arthur asked. The keeper nodded, "
               'though his look suggested that Arthur’s entry into this quiet village was quite an unusual sight.',
  'band_label': 'VocabQuest',
  'anchor_lexile': 850,
  'cefr_level': 'B1',
  'genre': 'literature',
  'word_count': 177,
  'topic': 'PET_part_4',
  'metadata': {'source': 'vocab_quest_promoted',
               'source_candidate_id': 'vq_3fcd767f3e99',
               'source_session_id': '3fcd767f-3e99-4c34-92b8-954eae7ab9cf',
               'generated_missing_skill': ''},
  'items': [{'id': 'ri_vq_3fcd767f3e99_main_idea',
             'item_order': 1,
             'skill': 'main_idea',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': 'What is the main idea of the story?',
             'choices': {'A': 'A man struggles to find a job in the western region.',
                         'B': 'A tired traveler arrives at a quiet hostel and feels out of place.',
                         'C': 'A school teacher teaches a lesson about local trade.',
                         'D': 'A car breaks down because it has no gas.'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The passage follows Arthur's journey and his awkward arrival at the hostel where he "
                                 'feels like an outsider.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_3fcd767f3e99_detail',
             'item_order': 2,
             'skill': 'detail',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "Why was Arthur feeling 'low' at the beginning of the passage?",
             'choices': {'A': 'Because he was lost in the southern region.',
                         'B': "Because he had forgotten his nephew's birthday.",
                         'C': 'Because he was tired and concerned about his car and trip.',
                         'D': 'Because he had run out of euros.'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': 'The passage says Arthur felt low while driving and worried about reaching his '
                                 'destination due to the lack of gas.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_3fcd767f3e99_inference',
             'item_order': 3,
             'skill': 'inference',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What can be inferred about the local people's attitude toward Arthur?",
             'choices': {'A': 'They are excited to meet a new visitor.',
                         'B': 'They find his presence strange or disruptive.',
                         'C': 'They are waiting for him to pay for his meal.',
                         'D': 'They think he is a famous person.'},
             'correct_choice': 'B',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': "The text mentions he might 'disappoint' the locals and his entry was an 'unusual "
                                 "sight', implying they see him as an outsider.",
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_3fcd767f3e99_vocabulary_context',
             'item_order': 4,
             'skill': 'vocabulary_context',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "In the text, what does 'permitted' mean?",
             'choices': {'A': 'Allowed', 'B': 'Required', 'C': 'Enjoyed', 'D': 'Forbidden'},
             'correct_choice': 'A',
             'rationales': {'A': "Arthur asks if the room is 'permitted' for him, which means he is checking if he is "
                                 'allowed to stay there.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': 'This choice is not the reviewed answer.',
                            'D': 'This choice is not the reviewed answer.'}},
            {'id': 'ri_vq_3fcd767f3e99_structure_author_purpose',
             'item_order': 5,
             'skill': 'structure_author_purpose',
             'difficulty_label': 'medium',
             'difficulty_offset': 0,
             'estimated_item_lexile': 850,
             'question_text': "What is the author's purpose in mentioning the headteacher writing a composition?",
             'choices': {'A': 'To describe the busy academic life of the village.',
                         'B': 'To show that the hostel is a place for quiet study.',
                         'C': 'To highlight the contrast between Arthur and the serious atmosphere.',
                         'D': 'To explain why the trade industry is important.'},
             'correct_choice': 'C',
             'rationales': {'A': 'This choice is not the reviewed answer.',
                            'B': 'This choice is not the reviewed answer.',
                            'C': "The author contrasts Arthur's 'crazy' arrival with the serious, studious nature of "
                                 'the local headteacher.',
                            'D': 'This choice is not the reviewed answer.'}}]}]
